param(
    [Parameter(Mandatory = $true)][string]$Tag,
    [switch]$SkipBuild
)

$ErrorActionPreference = 'Continue'
$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
Set-Location $root

$artifactRoot = Join-Path $root 'artifacts\genscene_acceptance'
$dir = Join-Path $artifactRoot $Tag
$currentMd = Join-Path $root 'CURRENT.md'
$failedMd = Join-Path $root 'CURRENT_FAILED.md'
New-Item -ItemType Directory -Force $dir | Out-Null

$results = [ordered]@{}
$hardFail = $false

function Report {
    param([string]$Name, [bool]$Ok, [string]$Detail)
    $status = 'FAIL'
    if ($Ok) { $status = 'PASS' }
    $script:results[$Name] = @{ ok = $Ok; detail = $Detail }
    Write-Host ("[{0}] {1}  {2}" -f $status, $Name.PadRight(22), $Detail)
    if (-not $Ok) { $script:hardFail = $true }
}

function Find-VsDevCmd {
    $candidates = @(
        'C:\Program Files\Microsoft Visual Studio\18\Community\Common7\Tools\VsDevCmd.bat',
        'C:\Program Files\Microsoft Visual Studio\18\Insiders\Common7\Tools\VsDevCmd.bat',
        'C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat'
    )
    foreach ($candidate in $candidates) {
        if (Test-Path $candidate) { return $candidate }
    }
    return $null
}

$prevTag = ''
if (Test-Path $currentMd) {
    $m = Select-String -Path $currentMd -Pattern 'Accepted tag:\s*`([^`]+)`' | Select-Object -First 1
    if ($m) { $prevTag = $m.Matches[0].Groups[1].Value }
}

$statusFile = Join-Path $dir 'git_status.txt'
git status --porcelain *> $statusFile
$statusLines = @(Get-Content $statusFile)
$cleanTree = $statusLines.Count -eq 0
Report 'clean_tree' $cleanTree $statusFile

$diffStat = Join-Path $dir 'git_diff_stat.txt'
git diff --stat *> $diffStat

$graphicsDiff = git diff -- tools/scene_graphics_gate.py
$addedMissingGate = $false
foreach ($line in $graphicsDiff) {
    if ($line -match '^\+.*missing_') { $addedMissingGate = $true }
}
$gateRatchetDetail = 'no added missing_* hard gates in scene_graphics_gate.py'
if ($addedMissingGate) { $gateRatchetDetail = 'added missing_* hard-gate lines detected in scene_graphics_gate.py' }
Report 'gate_ratchet_freeze' (-not $addedMissingGate) $gateRatchetDetail

$pyLog = Join-Path $dir 'python_compile.log'
python -m py_compile tools\scene_gen.py tools\scene_compiler.py tools\scene_quality_gate.py tools\scene_graphics_gate.py *> $pyLog
Report 'python_compile' ($LASTEXITCODE -eq 0) $pyLog

if ($SkipBuild) {
    Report 'release_build' $true 'skipped by -SkipBuild'
} else {
    $buildLog = Join-Path $dir 'release_build.log'
    $vs = Find-VsDevCmd
    if (-not $vs) {
        Report 'release_build' $false 'VsDevCmd.bat not found'
    } else {
        $cmdLine = '"' + $vs + '" -arch=x64 >nul && cmake --build build --config Release'
        & cmd.exe /d /s /c $cmdLine *> $buildLog
        Report 'release_build' ($LASTEXITCODE -eq 0) $buildLog
    }
}

$phase0Policy = 'dirty tree and old overlay-gate changes must not be accepted by assertion'
Report 'phase0_policy' $cleanTree $phase0Policy

$head = (git log -1 --pretty='%h %s' 2>$null)
$dirtyLine = 'CLEAN'
if (-not $cleanTree) {
    $dirtyLine = 'DIRTY: ' + (($statusLines | Select-Object -First 20) -join '; ')
}

$overall = 'GREEN - acceptable checkpoint (commit it now)'
if ($hardFail) { $overall = 'RED - DO NOT ACCEPT. Fix or revert before anything else.' }
$acceptedTag = $Tag
if ($hardFail) { $acceptedTag = $prevTag }

$lines = @(
    '# CURRENT -- machine-generated by the acceptance runner. DO NOT HAND-EDIT.'
    ''
    "Overall: **$overall**"
    ''
    "- Tag: ``$Tag``"
    "- Date: $(Get-Date -Format 'yyyy-MM-dd HH:mm')"
    "- Accepted tag: ``$acceptedTag``"
    "- Previous tag: ``$prevTag``"
    "- HEAD: $head"
    "- Tracked tree: $dirtyLine"
    ''
    '## Gates'
    ''
)
foreach ($key in $results.Keys) {
    $state = 'FAIL'
    if ($results[$key].ok) { $state = 'PASS' }
    $lines += "- **${key}**: $state -- $($results[$key].detail)"
}
$lines += @(
    ''
    '## Residuals'
    ''
    '    State is accepted only when this runner writes GREEN. Red output means fix or revert before new feature work.'
    ''
    '## Regression'
    ''
    "    Previous accepted tag: $prevTag"
    ''
    'Next steps live in `QUEUE.md` and `PLAN.md`. This file is state, nothing else.'
)

$target = $currentMd
if ($hardFail) { $target = $failedMd }
$lines | Out-File -FilePath $target -Encoding utf8
Write-Host ''
Write-Host ('State written to ' + $target)
if ($hardFail) { exit 1 }
exit 0
