param(
    [string]$SourceRoot = ""
)

$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($SourceRoot)) {
    $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
    $SourceRoot = Resolve-Path (Join-Path $scriptDir "..")
} else {
    $SourceRoot = Resolve-Path $SourceRoot
}

function Read-Text([string]$relativePath) {
    $path = Join-Path $SourceRoot $relativePath
    if (-not (Test-Path $path)) {
        throw "Missing required file: $relativePath"
    }
    return Get-Content -Raw -Path $path
}

function Assert-Contains([string]$text, [string]$needle, [string]$message) {
    if ($text.IndexOf($needle, [StringComparison]::Ordinal) -lt 0) {
        throw $message
    }
}

$cmake = Read-Text "CMakeLists.txt"
$engine = Read-Text "src/Core/Engine.cpp"
$input = Read-Text "src/Core/Engine_Input.cpp"
$ui = Read-Text "src/UI/GraphicsSettingsWindow.cpp"
$header = Read-Text "src/UI/GraphicsSettingsWindow.h"

Assert-Contains $cmake "src/UI/GraphicsSettingsWindow.cpp" "GraphicsSettingsWindow.cpp is not compiled by CMake."
Assert-Contains $cmake "src/UI/GraphicsSettingsWindow.h" "GraphicsSettingsWindow.h is not listed by CMake."

Assert-Contains $engine "UI/GraphicsSettingsWindow.h" "Engine.cpp does not include GraphicsSettingsWindow."
Assert-Contains $engine "GraphicsSettingsWindow::Initialize" "GraphicsSettingsWindow is not initialized."
Assert-Contains $engine "GraphicsSettingsWindow::Shutdown" "GraphicsSettingsWindow is not shut down."

Assert-Contains $input "UI/GraphicsSettingsWindow.h" "Engine_Input.cpp does not include GraphicsSettingsWindow."
Assert-Contains $input "GraphicsSettingsWindow::Toggle" "F8 path does not toggle GraphicsSettingsWindow."
Assert-Contains $input "GraphicsSettingsWindow::IsVisible" "ESC path does not check GraphicsSettingsWindow visibility."
Assert-Contains $input "GraphicsSettingsWindow::SetVisible(false)" "ESC path does not hide GraphicsSettingsWindow."

Assert-Contains $header "class GraphicsSettingsWindow" "GraphicsSettingsWindow public facade is missing."
Assert-Contains $ui "Graphics::RendererTuningState" "GraphicsSettingsWindow does not own RendererTuningState."
Assert-Contains $ui "Graphics::CaptureRendererTuningState" "GraphicsSettingsWindow does not capture renderer tuning state."
Assert-Contains $ui "Graphics::ApplyRendererTuningState" "GraphicsSettingsWindow does not apply renderer tuning state."
Assert-Contains $ui "BuildHealthState" "GraphicsSettingsWindow does not surface renderer health state."
Assert-Contains $ui "IDC_GFX_RT_SCHEDULER" "GraphicsSettingsWindow does not expose RT scheduler explanation panel."
Assert-Contains $ui "reflectionReadinessReason" "GraphicsSettingsWindow does not show RT reflection readiness reason."
Assert-Contains $ui "schedulerDisabledReason" "GraphicsSettingsWindow does not show RT scheduler skipped reason."
Assert-Contains $ui "IDC_GFX_RT_REFL_DENOISE" "GraphicsSettingsWindow does not expose RT reflection denoise tuning."
Assert-Contains $ui "IDC_GFX_RT_REFL_STRENGTH" "GraphicsSettingsWindow does not expose RT reflection composition tuning."
Assert-Contains $ui "IDC_GFX_RT_REFL_ROUGHNESS" "GraphicsSettingsWindow does not expose RT reflection roughness tuning."
Assert-Contains $ui "IDC_GFX_RT_REFL_HISTORY_CLAMP" "GraphicsSettingsWindow does not expose RT reflection history clamp tuning."
Assert-Contains $ui "IDC_GFX_RT_REFL_FIREFLY" "GraphicsSettingsWindow does not expose RT reflection firefly clamp tuning."
Assert-Contains $ui "IDC_GFX_RT_REFL_SCALE" "GraphicsSettingsWindow does not expose RT reflection scale tuning."
Assert-Contains $ui "reflectionDenoiseAlpha" "GraphicsSettingsWindow does not sync RT reflection denoise state."
Assert-Contains $ui "reflectionCompositionStrength" "GraphicsSettingsWindow does not sync RT reflection composition state."
Assert-Contains $ui "reflectionRoughnessThreshold" "GraphicsSettingsWindow does not sync RT reflection roughness state."
Assert-Contains $ui "reflectionHistoryMaxBlend" "GraphicsSettingsWindow does not sync RT reflection history clamp state."
Assert-Contains $ui "reflectionFireflyClampLuma" "GraphicsSettingsWindow does not sync RT reflection firefly clamp state."
Assert-Contains $ui "reflectionSignalScale" "GraphicsSettingsWindow does not sync RT reflection scale state."
Assert-Contains $ui "IDC_GFX_WARM" "GraphicsSettingsWindow does not expose warm color-grade tuning."
Assert-Contains $ui "IDC_GFX_COOL" "GraphicsSettingsWindow does not expose cool color-grade tuning."
Assert-Contains $ui "IDC_GFX_CONTRAST" "GraphicsSettingsWindow does not expose contrast tone tuning."
Assert-Contains $ui "IDC_GFX_SATURATION" "GraphicsSettingsWindow does not expose saturation tone tuning."
Assert-Contains $ui "IDC_GFX_GRADE_NEUTRAL" "GraphicsSettingsWindow does not expose neutral color-grade preset."
Assert-Contains $ui "IDC_GFX_GRADE_WARM_FILM" "GraphicsSettingsWindow does not expose warm film color-grade preset."
Assert-Contains $ui "IDC_GFX_GRADE_COOL_MOON" "GraphicsSettingsWindow does not expose cool moon color-grade preset."
Assert-Contains $ui "IDC_GFX_GRADE_BLEACH" "GraphicsSettingsWindow does not expose bleach-bypass color-grade preset."
Assert-Contains $ui "IDC_GFX_TONE_ACES" "GraphicsSettingsWindow does not expose ACES tone-mapper preset."
Assert-Contains $ui "IDC_GFX_TONE_REINHARD" "GraphicsSettingsWindow does not expose Reinhard tone-mapper preset."
Assert-Contains $ui "IDC_GFX_TONE_SOFT" "GraphicsSettingsWindow does not expose soft-filmic tone-mapper preset."
Assert-Contains $ui "IDC_GFX_TONE_PUNCHY" "GraphicsSettingsWindow does not expose punchy tone-mapper preset."
Assert-Contains $ui "colorGradePreset" "GraphicsSettingsWindow does not sync named color-grade preset state."
Assert-Contains $ui "toneMapperPreset" "GraphicsSettingsWindow does not sync named tone-mapper preset state."
Assert-Contains $ui "lighting.warm" "GraphicsSettingsWindow does not sync warm color-grade state."
Assert-Contains $ui "lighting.cool" "GraphicsSettingsWindow does not sync cool color-grade state."
Assert-Contains $ui "cinematicPost.contrast" "GraphicsSettingsWindow does not sync contrast tone state."
Assert-Contains $ui "cinematicPost.saturation" "GraphicsSettingsWindow does not sync saturation tone state."
Assert-Contains $ui "ApplyEnvironmentResidencyLoadControl" "GraphicsSettingsWindow does not expose environment residency controls."
Assert-Contains $ui "IDC_GFX_ENV_SELECT" "GraphicsSettingsWindow does not expose an environment dropdown."
Assert-Contains $ui "LoadEnvironmentManifest" "GraphicsSettingsWindow does not populate environments from the manifest."
Assert-Contains $ui "ApplySelectedEnvironmentFromGraphicsUI" "GraphicsSettingsWindow does not route environment dropdown selection."
Assert-Contains $ui "ApplyEnvironmentPresetControl" "GraphicsSettingsWindow does not apply selected environment presets."
Assert-Contains $ui "IDC_GFX_ENV_REAPPLY" "GraphicsSettingsWindow does not expose explicit environment reapply/reload control."
Assert-Contains $ui "IDC_GFX_ENV_ROTATION" "GraphicsSettingsWindow does not expose environment rotation control."
Assert-Contains $ui "environment.rotationDegrees" "GraphicsSettingsWindow does not sync environment rotation state."
Assert-Contains $ui "RendererLightingRigControl.h" "GraphicsSettingsWindow does not include lighting rig controls."
Assert-Contains $ui "IDC_GFX_RIG_STUDIO" "GraphicsSettingsWindow does not expose studio lighting rig control."
Assert-Contains $ui "IDC_GFX_RIG_WAREHOUSE" "GraphicsSettingsWindow does not expose top-down lighting rig control."
Assert-Contains $ui "IDC_GFX_RIG_SIDE" "GraphicsSettingsWindow does not expose side lighting rig control."
Assert-Contains $ui "IDC_GFX_RIG_LANTERNS" "GraphicsSettingsWindow does not expose lantern lighting rig control."
Assert-Contains $ui "ApplyLightingRigControl" "GraphicsSettingsWindow does not route lighting rig controls through the renderer applier."
Assert-Contains $ui "GetRegistry()" "GraphicsSettingsWindow does not pass the live scene registry to lighting rig controls."
Assert-Contains $ui "ApplyHeroVisualBaselineControls" "GraphicsSettingsWindow does not expose showcase baseline controls."
Assert-Contains $ui "SaveRendererTuningStateFile" "GraphicsSettingsWindow does not expose settings save."
Assert-Contains $ui "LoadRendererTuningStateFile" "GraphicsSettingsWindow does not expose settings load."
Assert-Contains $ui "IDC_GFX_VIGNETTE" "GraphicsSettingsWindow does not expose vignette control."
Assert-Contains $ui "IDC_GFX_LENS_DIRT" "GraphicsSettingsWindow does not expose lens dirt control."
Assert-Contains $ui "IDC_GFX_MOTION_BLUR" "GraphicsSettingsWindow does not expose motion blur control."
Assert-Contains $ui "IDC_GFX_DOF" "GraphicsSettingsWindow does not expose depth-of-field control."
Assert-Contains $ui "IDC_GFX_CINEMATIC_POST" "GraphicsSettingsWindow does not expose cinematic post enable control."
Assert-Contains $ui "cinematicPost.motionBlur" "GraphicsSettingsWindow does not sync motion blur state."
Assert-Contains $ui "cinematicPost.depthOfField" "GraphicsSettingsWindow does not sync depth-of-field state."
Assert-Contains $ui "IDC_GFX_WATER_LENGTH" "GraphicsSettingsWindow does not expose water wavelength control."
Assert-Contains $ui "IDC_GFX_WATER_SPEED" "GraphicsSettingsWindow does not expose water speed control."
Assert-Contains $ui "IDC_GFX_WATER_SECONDARY" "GraphicsSettingsWindow does not expose secondary water amplitude control."
Assert-Contains $ui "water.waveLength" "GraphicsSettingsWindow does not sync water wavelength state."
Assert-Contains $ui "water.waveSpeed" "GraphicsSettingsWindow does not sync water speed state."
Assert-Contains $ui "water.secondaryAmplitude" "GraphicsSettingsWindow does not sync secondary water amplitude state."
Assert-Contains $ui "IDC_GFX_WATER_ROUGHNESS" "GraphicsSettingsWindow does not expose water roughness control."
Assert-Contains $ui "IDC_GFX_WATER_FRESNEL" "GraphicsSettingsWindow does not expose water Fresnel control."
Assert-Contains $ui "water.roughness" "GraphicsSettingsWindow does not sync water roughness state."
Assert-Contains $ui "water.fresnelStrength" "GraphicsSettingsWindow does not sync water Fresnel state."
Assert-Contains $ui "IDC_GFX_BACKGROUND_VISIBLE" "GraphicsSettingsWindow does not expose background visibility control."
Assert-Contains $ui "IDC_GFX_BACKGROUND_EXPOSURE" "GraphicsSettingsWindow does not expose background exposure control."
Assert-Contains $ui "IDC_GFX_BACKGROUND_BLUR" "GraphicsSettingsWindow does not expose background blur control."
Assert-Contains $ui "IDC_GFX_SSAO_BIAS" "GraphicsSettingsWindow does not expose SSAO bias control."
Assert-Contains $ui "screenSpace.ssaoBias" "GraphicsSettingsWindow does not sync SSAO bias state."
Assert-Contains $ui "IDC_GFX_SSR_DISTANCE" "GraphicsSettingsWindow does not expose SSR max-distance control."
Assert-Contains $ui "IDC_GFX_SSR_THICKNESS" "GraphicsSettingsWindow does not expose SSR thickness control."
Assert-Contains $ui "IDC_GFX_SSR_STRENGTH" "GraphicsSettingsWindow does not expose SSR strength control."
Assert-Contains $ui "screenSpace.ssrMaxDistance" "GraphicsSettingsWindow does not sync SSR max-distance state."
Assert-Contains $ui "screenSpace.ssrThickness" "GraphicsSettingsWindow does not sync SSR thickness state."
Assert-Contains $ui "screenSpace.ssrStrength" "GraphicsSettingsWindow does not sync SSR strength state."
Assert-Contains $ui "IDC_GFX_FOG_HEIGHT" "GraphicsSettingsWindow does not expose fog height control."
Assert-Contains $ui "IDC_GFX_FOG_FALLOFF" "GraphicsSettingsWindow does not expose fog falloff control."
Assert-Contains $ui "atmosphere.fogHeight" "GraphicsSettingsWindow does not sync fog height state."
Assert-Contains $ui "atmosphere.fogFalloff" "GraphicsSettingsWindow does not sync fog falloff state."
Assert-Contains $ui "IDC_GFX_PARTICLE_DENSITY" "GraphicsSettingsWindow does not expose particle density control."
Assert-Contains $ui "IDC_GFX_PARTICLE_QUALITY" "GraphicsSettingsWindow does not expose particle quality control."
Assert-Contains $ui "IDC_GFX_PARTICLE_BLOOM" "GraphicsSettingsWindow does not expose particle bloom control."
Assert-Contains $ui "IDC_GFX_PARTICLE_SOFT_DEPTH" "GraphicsSettingsWindow does not expose particle soft-depth control."
Assert-Contains $ui "IDC_GFX_PARTICLE_WIND" "GraphicsSettingsWindow does not expose particle wind control."
Assert-Contains $ui "IDC_GFX_PARTICLE_EFFECT_SELECT" "GraphicsSettingsWindow does not expose particle effect preset control."
Assert-Contains $ui "particles.qualityScale" "GraphicsSettingsWindow does not sync particle quality state."
Assert-Contains $ui "particles.bloomContribution" "GraphicsSettingsWindow does not sync particle bloom state."
Assert-Contains $ui "particles.softDepthFade" "GraphicsSettingsWindow does not sync particle soft-depth state."
Assert-Contains $ui "particles.windInfluence" "GraphicsSettingsWindow does not sync particle wind state."
Assert-Contains $ui "particles.effectPreset" "GraphicsSettingsWindow does not sync particle effect preset state."
Assert-Contains $ui "IDC_GFX_BOOKMARK_HERO" "GraphicsSettingsWindow does not expose hero camera bookmark control."
Assert-Contains $ui "IDC_GFX_BOOKMARK_REFLECTION" "GraphicsSettingsWindow does not expose reflection camera bookmark control."
Assert-Contains $ui "IDC_GFX_BOOKMARK_MATERIALS" "GraphicsSettingsWindow does not expose material overview camera bookmark control."
Assert-Contains $ui "ApplyShowcaseCameraBookmark" "GraphicsSettingsWindow does not route camera bookmark controls to Engine."
Assert-Contains $engine "CORTEX_GRAPHICS_SETTINGS_PATH" "Engine does not support user graphics settings path override."

Write-Host "Graphics UI contract tests passed"
